export const categoriesString = [
  'animal', 'career', 'celebrity', 'dev', 'explicit', 'fashion',
  'food', 'history', 'money', 'movie', 'music', 'political', 'religion',
  'science', 'sport', 'travel', 'random',
]

export const categoriesArray = [
  {
    categories: 'animal',
    createdAt: '',
    iconUrl: '',
    id: '01',
    updatedAt: '',
    url: '',
    value: 'animal',
  },
  {
    categories: 'career',
    createdAt: '',
    iconUrl: '',
    id: '02',
    updatedAt: '',
    url: '',
    value: 'career',
  },
  {
    categories: 'celebrity',
    createdAt: '',
    iconUrl: '',
    id: '03',
    updatedAt: '',
    url: '',
    value: 'celebrity',
  },
  {
    categories: 'dev',
    createdAt: '',
    iconUrl: '',
    id: '04',
    updatedAt: '',
    url: '',
    value: 'dev',
  },
  {
    categories: 'explicit',
    createdAt: '',
    iconUrl: '',
    id: '05',
    updatedAt: '',
    url: '',
    value: 'explicit',
  },
  {
    categories: 'fashion',
    createdAt: '',
    iconUrl: '',
    id: '06',
    updatedAt: '',
    url: '',
    value: 'fashion',
  },
  {
    categories: 'food',
    createdAt: '',
    iconUrl: '',
    id: '07',
    updatedAt: '',
    url: '',
    value: 'food',
  },
  {
    categories: 'history',
    createdAt: '',
    iconUrl: '',
    id: '08',
    updatedAt: '',
    url: '',
    value: 'history',
  },
  {
    categories: 'money',
    createdAt: '',
    iconUrl: '',
    id: '09',
    updatedAt: '',
    url: '',
    value: `money It's the end of the month and the weekend I'ma spend this check, everything on me, yeah I'ma tip myself, I'ma spend it on myself
I'ma drop it like it's pouring, I'ma pour it on myself…`,
  },
  {
    categories: 'movie',
    createdAt: '',
    iconUrl: '',
    id: '10',
    updatedAt: '',
    url: '',
    value: 'movie',
  },
  {
    categories: 'political',
    createdAt: '',
    iconUrl: '',
    id: '11',
    updatedAt: '',
    url: '',
    value: 'political',
  },
  {
    categories: 'religion',
    createdAt: '',
    iconUrl: '',
    id: '12',
    updatedAt: '',
    url: '',
    value: 'religion',
  },
  {
    categories: 'science',
    createdAt: '',
    iconUrl: '',
    id: '13',
    updatedAt: '',
    url: '',
    value: 'science',
  },
  {
    categories: 'sport',
    createdAt: '',
    iconUrl: '',
    id: '14',
    updatedAt: '',
    url: '',
    value: 'sport',
  },
  {
    categories: 'travel',
    createdAt: '',
    iconUrl: '',
    id: '15',
    updatedAt: '',
    url: '',
    value: 'travel',
  },
  {
    categories: 'random',
    createdAt: '',
    iconUrl: '',
    id: '16',
    updatedAt: '',
    url: '',
    value: 'random',
  },
]
